global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'youtube-bot-monitor'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'youtube-bot'
    static_configs:
      - targets: ['youtube-bot:3000']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: http
    
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
      
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
